[package]
name = "solitaire"
version = "0.1.0"
authors = ["Martin Grenfell <martin.grenfell@gmail.com>"]

[dependencies]
rand = "*"
unicode_names = { git = 'https://github.com/antifuchs/unicode_names', branch = 'fix-for-rust-1-10' }
itertools = "*"
colored = "*"
